grafana:
  enabled: true
  defaultDashboardsEnabled: true

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /var/lib/grafana/dashboards/default

prometheus:
  prometheusSpec:
    # Additional scrape configurations for blackbox exporter
    additionalScrapeConfigs:
      - job_name: "blackbox_exporter"
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
              - https://optit.in/devops-as-a-service/
              - www.parkquility.com
              - 10.10.30.921:9208
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: kube-prometheus-blackbox-exporter:9115

    # Custom and default alert rules configuration
    ruleSelector:                   
      matchExpressions:
        - key: role
          operator: In
          values: ["alert-rules1"]
commonLabels: 
  role: alert-rules1

alertmanager:
  enabled: true

  alertmanagerSpec:
    replicas: 1
    externalUrl: http://alertmanager-operated.monitoring.svc:9093

  config:
    global:
      smtp_smarthost: 'smtp.gmail.com:587'  # Gmail SMTP server
      smtp_from: 'msdbvsr07@gmail.com'   # Your Gmail address
      smtp_auth_username: 'msdbvsr07@gmail.com'  # Gmail email address
      smtp_auth_password: 'srva qjrm apzq whzq'  # Gmail App password
      smtp_require_tls: true                # Enforce TLS
      resolve_timeout: 5m

    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 5m
      receiver: 'email'

      # Route only critical alerts to email
      routes:
        - matchers:
            - job = blackbox_exporter    # Only email critical severity alerts
          receiver: 'email'

    receivers:
      - name: 'email'
        email_configs:
          - to: 'navaneethravi2@gmail.com'  # Your email address
            require_tls: true
            send_resolved: false    # Do not send resolved state alerts

    templates:
      - '/etc/alertmanager/config/*.tmpl'
